name: Test 1

on:
  workflow_dispatch:
    inputs:
      pull-number:
        description: 'The pull request number from which the slash command was dispatched'
        required: true
      pull-sha:
        description: 'SHA of the head of the pull request from which the slash command was dispatched'
        required: true

jobs:
  test:
    name: Test 1
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: true
          repository: StrikerRUS/LightGBM
          ref: "refs/pull/${{ github.event.inputs.pull-number }}/merge"
      - name: Send init status
        if: ${{ always() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: $GITHUB_WORKSPACE/.ci/set_commit_status.sh "${{ github.workflow }}" "pending" "${{ github.event.inputs.pull-sha }}"
      - name: Test
        run: |
            sleep 30s
            exit -1
      - name: Send final status
        if: ${{ always() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: $GITHUB_WORKSPACE/.ci/set_commit_status.sh "${{ github.workflow }}" "${{ job.status }}" "${{ github.event.inputs.pull-sha }}"
