name: Test 2

on:
  repository_dispatch:
    types: [gha_run_2]

jobs:
  test:
    name: Test 2
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: true
          repository: StrikerRUS/LightGBM
          ref: "refs/pull/${{ github.event.client_payload.pr_number }}/merge"
      - name: Send init status
        if: ${{ always() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: $GITHUB_WORKSPACE/.ci/set_commit_status.sh "${{ github.workflow }}" "pending" "${{ github.event.client_payload.pr_sha }}"
      - name: Test
        run: |
            sleep 30s
            exit 0
      - name: Send final status
        if: ${{ always() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: $GITHUB_WORKSPACE/.ci/set_commit_status.sh "${{ github.workflow }}" "${{ job.status }}" "${{ github.event.client_payload.pr_sha }}"
