name: Test 2

on:
  repository_dispatch:
    types: [gha_run_2]

jobs:
  test:
    name: Test 2
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: true
          repository: StrikerRUS/LightGBM
          ref: "refs/pull/${{ github.event.client_payload.pr_number }}/merge"
      - name: Send init status
        id: init_status
        if: ${{ always() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: |
          $GITHUB_WORKSPACE/.ci/set_commit_status.sh "${{ github.workflow }}" "pending" "${{ github.event.client_payload.pr_sha }}"
          $GITHUB_WORKSPACE/.ci/create_or_update_review_comment.sh \
            "${{ github.event.client_payload.pr_number }}" \
            "${{ github.event.client_payload.comment_number }}" \
            "create" \
            "Workflow **${{ github.workflow }}** has been triggered! 🚀\r\n${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
      - name: Test
        run: |
            sleep 30s
            $GITHUB_WORKSPACE/.ci/test_2.sh
      - name: Send final status
        if: ${{ always() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: |
          $GITHUB_WORKSPACE/.ci/set_commit_status.sh "${{ github.workflow }}" "${{ job.status }}" "${{ github.event.client_payload.pr_sha }}"
          $GITHUB_WORKSPACE/.ci/create_or_update_review_comment.sh \
            "${{ github.event.client_payload.pr_number }}" \
            "${{ steps.init_status.outputs.reply_id }}" \
            "append" \
            "Status: ${{ job.status }}."
      - name: Rerun main workflow
        if: ${{ success() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: python $GITHUB_WORKSPACE/.ci/rerun_workflow.py "test_main.yml" "${{ github.event.client_payload.pr_number }}" "${{ github.event.client_payload.pr_branch }}" || true
