name: Test 1

on:
  repository_dispatch:
    types: [gha_run_1]

jobs:
  test:
    name: Test 1
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: true
          repository: StrikerRUS/LightGBM
          ref: "refs/pull/${{ github.event.client_payload.pr_number }}/merge"
      - name: Send init status
        id: init_status
        if: ${{ always() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: |
          $GITHUB_WORKSPACE/.ci/set_commit_status.sh "${{ github.workflow }}" "pending" "${{ github.event.client_payload.pr_sha }}"
          $GITHUB_WORKSPACE/.ci/append_comment.sh \
            "${{ github.event.client_payload.pr_number }}" \
            "${{ github.event.client_payload.comment_number }}" \
            "Workflow **${{ github.workflow }}** has been triggered! 🚀\r\n${GITHUB_SERVER_URL}/StrikerRUS/LightGBM/actions/runs/${GITHUB_RUN_ID}"
      - name: Test
        run: |
            sleep 30s
            $GITHUB_WORKSPACE/.ci/test_1.sh
      - name: Send final status
        if: ${{ always() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: |
          $GITHUB_WORKSPACE/.ci/set_commit_status.sh "${{ github.workflow }}" "${{ job.status }}" "${{ github.event.client_payload.pr_sha }}"
          $GITHUB_WORKSPACE/.ci/append_comment.sh \
            "${{ github.event.client_payload.pr_number }}" \
            "${{ github.event.client_payload.comment_number }}" \
            "Status: ${{ job.status }}."
      - name: Rerun main workflow
        if: ${{ success() }}
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: |
          python $GITHUB_WORKSPACE/.ci/rerun_workflow.py \
            "test_main.yml" \
            "${{ github.event.client_payload.pr_number }}" \
            "${{ github.event.client_payload.pr_branch }}" \
            || true
