name: Test main

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: true
      - name: Dump test
        shell: bash
        run: |
            sleep 20s
            exit 0
  all-successful:
    # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: false
      - name: Note that all tests succeeded
        env:
          SECRETS_WORKFLOW: ${{ secrets.WORKFLOW }}
        run: |
            all_success="yes"
            workflows=("Test 1"
                       "Test 2")
            for i in "${workflows[@]}"; do
                status=$(python "$GITHUB_WORKSPACE/.ci/get_workflow_status.py" "$i") || all_success="no"
                $GITHUB_WORKSPACE/.ci/set_commit_status.sh "$i" "$status" "${{ github.event.pull_request.head.sha }}"
            done
            if [[ $check_succeeded == "no" ]]; then
                exit -1
            fi
