name: Triggering comments

on:
  pull_request_review_comment:
    types: [created]

jobs:
  triggering-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger tests 1
      if: github.event.comment.body == '/gha run 1' && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association)
      run: |
        test=`cat $GITHUB_EVENT_PATH`
        data=$(jq -n \
          --arg event_type "gha_run_1" \
          --arg github "$test" \
          '{"event_type":$event_type,"client_payload":{"github":$github}}')
        curl -sL \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.WORKFLOW }}" \
        -d "$data" \
        "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/dispatches"

    - name: Trigger tests 2
      if: github.event.comment.body == '/gha run 2' && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association)
      run: |
        data=$(jq -n \
          --arg event_type "gha_run_2" \
          --arg github "${{ toJson(github) }}" \
          '{"event_type":$event_type,"client_payload":{"github":$github}}')
        curl -sL \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.WORKFLOW }}" \
        -d "$data" \
        "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/dispatches"
