name: Triggering comments

on:
  issue_comment:
    types: [created]

jobs:
  triggering-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger tests 1
      uses: peter-evans/slash-command-dispatch@v2
      with:
        token: ${{ secrets.WORKFLOW }}
        reaction-token: ${{ github.token }}
        permission: write
        issue-type: pull-request
        allow-edits: false
        event-type-suffix: "-command"
        commands: gha-run-1
    - name: Trigger tests 2
      uses: peter-evans/slash-command-dispatch@v2
      with:
        token: ${{ secrets.WORKFLOW }}
        reaction-token: ${{ github.token }}
        permission: write
        issue-type: pull-request
        allow-edits: false
        event-type-suffix: "-command"
        commands: gha-run-2
