name: Triggering comments

on:
  issue_comment:
    types: [created]

jobs:
  triggering-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger tests 1
      uses: peter-evans/slash-command-dispatch@v2
      with:
        token: ${{ secrets.WORKFLOW }}
        reaction-token: ${{ github.token }}
        permission: write
        issue-type: pull-request
        allow-edits: false
        dispatch-type: workflow
        event-type-suffix: ""
        commands: gha-run-1
        static-args: |
          pull-number=${{ github.event.pull_request.number }}
          pull-sha=${{ github.event.pull_request.head.sha }}
    - name: Trigger tests 2
      uses: peter-evans/slash-command-dispatch@v2
      with:
        token: ${{ secrets.WORKFLOW }}
        reaction-token: ${{ github.token }}
        permission: write
        issue-type: pull-request
        allow-edits: false
        dispatch-type: workflow
        event-type-suffix: ""
        commands: gha-run-2
        static-args: |
          pull-number=${{ github.event.pull_request.number }}
          pull-sha=${{ github.event.pull_request.head.sha }}
