name: Triggering comments

on:
  pull_request_review_comment:
    types: [created]

jobs:
  triggering-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger tests 1
      if: github.event.comment.body == '/gha run 1' && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association)
      run: |
        data=$(jq -n \
          --arg event_type "gha_run_1" \
          --arg pr_number "${{ github.event.pull_request.number }}" \
          --arg pr_sha "${{ github.event.pull_request.head.sha }}" \
          --arg pr_branch "${{ github.event.pull_request.head.ref }}" \
          --arg comment_number "${{ github.event.comment.id }}" \
          '{"event_type":$event_type,"client_payload":{"pr_number":$pr_number,"pr_sha":$pr_sha,"pr_branch":$pr_branch,"comment_number":$comment_number}}')
        curl -sL \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.WORKFLOW }}" \
        -d "$data" \
        "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/dispatches"

    - name: Trigger tests 2
      if: github.event.comment.body == '/gha run 2' && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association)
      run: |
        data=$(jq -n \
          --arg event_type "gha_run_2" \
          --arg pr_number "${{ github.event.pull_request.number }}" \
          --arg pr_sha "${{ github.event.pull_request.head.sha }}" \
          --arg pr_branch "${{ github.head_ref }}" \
          --arg comment_number "${{ github.event.comment.id }}" \
          '{"event_type":$event_type,"client_payload":{"pr_number":$pr_number,"pr_sha":$pr_sha,"pr_branch":$pr_branch,"comment_number":$comment_number}}')
        curl -sL \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.WORKFLOW }}" \
        -d "$data" \
        "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/dispatches"
