name: Triggering comments

on:
  issue_comment:
    types: [created]

jobs:
  triggering-tests:
    if: github.event.issue.pull_request && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association)
    runs-on: ubuntu-latest

    steps:
    - name: Trigger tests 1
      if: github.event.comment.body == '/gha run 1'
      run: |
        pr=$(curl -sL \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.WORKFLOW }}" \
          "${{ github.event.issue.pull_request.url }}")
        data=$(jq -n \
          --arg event_type "gha_run_1" \
          --arg pr_number "$(echo $pr | jq '.number')" \
          --arg pr_sha "$(echo $pr | jq '.head.sha')" \
          --arg pr_branch "$(echo $pr | jq '.head.ref')" \
          --arg comment_number "${{ github.event.comment.id }}" \
          '{"event_type":$event_type,"client_payload":{"pr_number":$pr_number,"pr_sha":$pr_sha,"pr_branch":$pr_branch,"comment_number":$comment_number}}')
        curl -sL \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.WORKFLOW }}" \
        -d "$data" \
        "${GITHUB_API_URL}/repos/StrikerRUS/LightGBM/dispatches"

    - name: Trigger tests 2
      if: github.event.comment.body == '/gha run 2'
      run: |
        pr=$(curl -sL \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.WORKFLOW }}" \
          "${{ github.event.issue.pull_request.url }}")
        data=$(jq -n \
          --arg event_type "gha_run_2" \
          --arg pr_number "$(echo $pr | jq '.number')" \
          --arg pr_sha "$(echo $pr | jq '.head.sha')" \
          --arg pr_branch "$(echo $pr | jq '.head.ref')" \
          --arg comment_number "${{ github.event.comment.id }}" \
          '{"event_type":$event_type,"client_payload":{"pr_number":$pr_number,"pr_sha":$pr_sha,"pr_branch":$pr_branch,"comment_number":$comment_number}}')
        curl -sL \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.WORKFLOW }}" \
        -d "$data" \
        "${GITHUB_API_URL}/repos/StrikerRUS/LightGBM/dispatches"
