name: Triggering comments

on:
  issue_comment:
    types: [created]

jobs:
  triggering-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Get PR details
      id: pr_details
      run: |
        url="${{ github.event.issue.pull_request.url }}"
        number="${url##*/}"
        sha=$(curl -sL \
                -H "Accept: application/vnd.github.v3+json" \
                 $url \
              | jq '.head.sha')
        echo $number
        echo $sha
        echo "::set-output name=pull_number::${number}"
        echo "::set-output name=pull_sha::${sha}"
    - name: Trigger tests 1
      uses: peter-evans/slash-command-dispatch@v2
      with:
        token: ${{ secrets.WORKFLOW }}
        reaction-token: ${{ github.token }}
        permission: write
        issue-type: pull-request
        allow-edits: false
        dispatch-type: workflow
        ref: "refs/pull/${{ steps.pr_details.outputs.pull_number }}/merge"
        event-type-suffix: ""
        commands: gha-run-1
        static-args: |
          pull-number=${{ steps.pr_details.outputs.pull_number }}
          pull-sha=${{ steps.pr_details.outputs.pull_sha }}
    - name: Trigger tests 2
      uses: peter-evans/slash-command-dispatch@v2
      with:
        token: ${{ secrets.WORKFLOW }}
        reaction-token: ${{ github.token }}
        permission: write
        issue-type: pull-request
        allow-edits: false
        dispatch-type: workflow
        ref: "refs/pull/${{ steps.pr_details.outputs.pull_number }}/merge"
        event-type-suffix: ""
        commands: gha-run-2
        static-args: |
          pull-number=${{ steps.pr_details.outputs.pull_number }}
          pull-sha=${{ steps.pr_details.outputs.pull_sha }}
    - name: Delete run log
      run: |
        curl -sL \
        -X DELETE \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $SECRETS_WORKFLOW" \
        "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/actions/runs/${{ github.run_id }}"
